# Project Goals:

## Other Links:

[Markdown Cheatsheet](https://www.markdownguide.org/basic-syntax/)

[Link To Google Document](https://docs.google.com/document/d/1Spref_pjFamfD-KR-_QiNYEyXASlaG7z9inboxcsCjs/edit?usp=sharing)

## Flatiron Notes

Tanzania, as a developing country, struggles with providing clean water to its population of over 57,000,000. There are many water points already established in the country, but some are in need of repair while others have failed altogether.

Build a classifier to predict the condition of a water well, using information about the sort of pump, when it was installed, etc. Your audience could be an NGO focused on locating wells needing repair, or the Government of Tanzania looking to find patterns in non-functional wells to influence how new wells are built. Note that this is a ternary classification problem by default, but can be engineered to be binary.


Example Options: 
* Locating wells in need of repair
* patterns in non-functional wells

[source of data](https://www.drivendata.org/competitions/7/pump-it-up-data-mining-the-water-table/page/23/)

## Project Description

### The features in this dataset

Your goal is to predict the operating condition of a waterpoint for each record in the dataset. You are provided the following set of information about the waterpoints:

* amount_tsh - Total static head (amount water available to waterpoint)
* date_recorded - The date the row was entered
* funder - Who funded the well
* gps_height - Altitude of the well
* installer - Organization that installed the well
* longitude - GPS coordinate
* latitude - GPS coordinate
* wpt_name - Name of the waterpoint if there is one
* num_private -
* basin - Geographic water basin
* subvillage - Geographic location
* region - Geographic location
* region_code - Geographic location (coded)
* district_code - Geographic location (coded)
* lga - Geographic location
* ward - Geographic location
* population - Population around the well
* public_meeting - True/False
* recorded_by - Group entering this row of data
* scheme_management - Who operates the waterpoint
* scheme_name - Who operates the waterpoint
* permit - If the waterpoint is permitted
* construction_year - Year the waterpoint was constructed
* extraction_type - The kind of extraction the waterpoint uses
* extraction_type_group - The kind of extraction the waterpoint uses
* extraction_type_class - The kind of extraction the waterpoint uses
* management - How the waterpoint is managed
* management_group - How the waterpoint is managed
* payment - What the water costs
* payment_type - What the water costs
* water_quality - The quality of the water
* quality_group - The quality of the water
* quantity - The quantity of water
* quantity_group - The quantity of water
* source - The source of the water
* source_type - The source of the water
* source_class - The source of the water
* waterpoint_type - The kind of waterpoint
* waterpoint_type_group - The kind of waterpoint

### The Labels In The Dataset

The labels in this dataset are simple. There are three possible values:

* functional - the waterpoint is operational and there are no repairs needed
* functional needs repair - the waterpoint is operational, but needs repairs
* non functional - the waterpoint is not operational

# Initial Data Prep

In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

## First problem: 

What in the world is with this data split

Can I combine the training? Or is that redundant?

Need to first figure out what my data looks like.

In [33]:
df_test = pd.read_csv('./Data/test_set.csv')
df_train_1 = pd.read_csv('./Data/training_set_labels.csv')
df_train_2 = pd.read_csv('./Data/training_set_values.csv')

In [34]:
df_test

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,...,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
0,50785,0.0,2013-02-04,Dmdd,1996,DMDD,35.290799,-4.059696,Dinamu Secondary School,0,...,never pay,soft,good,seasonal,seasonal,rainwater harvesting,rainwater harvesting,surface,other,other
1,51630,0.0,2013-02-04,Government Of Tanzania,1569,DWE,36.656709,-3.309214,Kimnyak,0,...,never pay,soft,good,insufficient,insufficient,spring,spring,groundwater,communal standpipe,communal standpipe
2,17168,0.0,2013-02-01,NaN,1567,NaN,34.767863,-5.004344,Puma Secondary,0,...,never pay,soft,good,insufficient,insufficient,rainwater harvesting,rainwater harvesting,surface,other,other
3,45559,0.0,2013-01-22,Finn Water,267,FINN WATER,38.058046,-9.418672,Kwa Mzee Pange,0,...,unknown,soft,good,dry,dry,shallow well,shallow well,groundwater,other,other
4,49871,500.0,2013-03-27,Bruder,1260,BRUDER,35.006123,-10.950412,Kwa Mzee Turuka,0,...,monthly,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14845,39307,0.0,2011-02-24,Danida,34,Da,38.852669,-6.582841,Kwambwezi,0,...,never pay,soft,good,enough,enough,river,river/lake,surface,communal standpipe,communal standpipe
14846,18990,1000.0,2011-03-21,Hiap,0,HIAP,37.451633,-5.350428,Bonde La Mkondoa,0,...,annually,salty,salty,insufficient,insufficient,shallow well,shallow well,groundwater,hand pump,hand pump
14847,28749,0.0,2013-03-04,NaN,1476,NaN,34.739804,-4.585587,Bwawani,0,...,never pay,soft,good,insufficient,insufficient,dam,dam,surface,communal standpipe,communal standpipe
14848,33492,0.0,2013-02-18,Germany,998,DWE,35.432732,-10.584159,Kwa John,0,...,never pay,soft,good,insufficient,insufficient,river,river/lake,surface,communal standpipe,communal standpipe
14849,68707,0.0,2013-02-13,Government Of Tanzania,481,Government,34.765054,-11.226012,Kwa Mzee Chagala,0,...,never pay,soft,good,dry,dry,spring,spring,groundwater,communal standpipe,communal standpipe

In [35]:
# list the columns in dataset df_test
df_test.columns

Index(['id', 'amount_tsh', 'date_recorded', 'funder', 'gps_height',
       'installer', 'longitude', 'latitude', 'wpt_name', 'num_private',
       'basin', 'subvillage', 'region', 'region_code', 'district_code', 'lga',
       'ward', 'population', 'public_meeting', 'recorded_by',
       'scheme_management', 'scheme_name', 'permit', 'construction_year',
       'extraction_type', 'extraction_type_group', 'extraction_type_class',
       'management', 'management_group', 'payment', 'payment_type',
       'water_quality', 'quality_group', 'quantity', 'quantity_group',
       'source', 'source_type', 'source_class', 'waterpoint_type',
       'waterpoint_type_group'],
      dtype='object')

In [36]:
len(df_test)

14850

So there are 14,850 rows in the dataset.

In [37]:
len(df_test.columns)

40

And 40 features.

Let's get a layout of the features in the dataset.

In [38]:
df_train_1

          id    status_group
0      69572      functional
1       8776      functional
2      34310      functional
3      67743  non functional
4      19728      functional
...      ...             ...
59395  60739      functional
59396  27263      functional
59397  37057      functional
59398  31282      functional
59399  26348      functional

[59400 rows x 2 columns]

In [39]:
# What are the possible values for the column 'status_group'?
df_train_1['status_group'].unique()

array(['functional', 'non functional', 'functional needs repair'],
      dtype=object)

***So I'm gonna have to turn this from a ternary project into a binary project.***

In [40]:
df_train_2

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,...,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
0,69572,6000.0,2011-03-14,Roman,1390,Roman,34.938093,-9.856322,none,0,...,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
1,8776,0.0,2013-03-06,Grumeti,1399,GRUMETI,34.698766,-2.147466,Zahanati,0,...,never pay,soft,good,insufficient,insufficient,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe
2,34310,25.0,2013-02-25,Lottery Club,686,World vision,37.460664,-3.821329,Kwa Mahundi,0,...,per bucket,soft,good,enough,enough,dam,dam,surface,communal standpipe multiple,communal standpipe
3,67743,0.0,2013-01-28,Unicef,263,UNICEF,38.486161,-11.155298,Zahanati Ya Nanyumbu,0,...,never pay,soft,good,dry,dry,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe
4,19728,0.0,2011-07-13,Action In A,0,Artisan,31.130847,-1.825359,Shuleni,0,...,never pay,soft,good,seasonal,seasonal,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59395,60739,10.0,2013-05-03,Germany Republi,1210,CES,37.169807,-3.253847,Area Three Namba 27,0,...,per bucket,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
59396,27263,4700.0,2011-05-07,Cefa-njombe,1212,Cefa,35.249991,-9.070629,Kwa Yahona Kuvala,0,...,annually,soft,good,enough,enough,river,river/lake,surface,communal standpipe,communal standpipe
59397,37057,0.0,2011-04-11,NaN,0,NaN,34.017087,-8.750434,Mashine,0,...,monthly,fluoride,fluoride,enough,enough,machine dbh,borehole,groundwater,hand pump,hand pump
59398,31282,0.0,2011-03-08,Malec,0,Musa,35.861315,-6.378573,Mshoro,0,...,never pay,soft,good,insufficient,insufficient,shallow well,shallow well,groundwater,hand pump,hand pump
59399,26348,0.0,2011-03-23,World Bank,191,World,38.104048,-6.747464,Kwa Mzee Lugawa,0,...,on failure,salty,salty,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump

In [41]:
df_train_2.columns

Index(['id', 'amount_tsh', 'date_recorded', 'funder', 'gps_height',
       'installer', 'longitude', 'latitude', 'wpt_name', 'num_private',
       'basin', 'subvillage', 'region', 'region_code', 'district_code', 'lga',
       'ward', 'population', 'public_meeting', 'recorded_by',
       'scheme_management', 'scheme_name', 'permit', 'construction_year',
       'extraction_type', 'extraction_type_group', 'extraction_type_class',
       'management', 'management_group', 'payment', 'payment_type',
       'water_quality', 'quality_group', 'quantity', 'quantity_group',
       'source', 'source_type', 'source_class', 'waterpoint_type',
       'waterpoint_type_group'],
      dtype='object')

In [42]:
len(df_train_2.columns)

40

In [43]:
df_train_2.head().T

,0,1,2,3,4
id,69572,8776,34310,67743,19728
amount_tsh,6000,0,25,0,0
date_recorded,2011-03-14,2013-03-06,2013-02-25,2013-01-28,2011-07-13
funder,Roman,Grumeti,Lottery Club,Unicef,Action In A
gps_height,1390,1399,686,263,0
installer,Roman,GRUMETI,World vision,UNICEF,Artisan
longitude,34.9381,34.6988,37.4607,38.4862,31.1308
latitude,-9.85632,-2.14747,-3.82133,-11.1553,-1.82536
wpt_name,none,Zahanati,Kwa Mahundi,Zahanati Ya Nanyumbu,Shuleni
num_private,0,0,0,0,0
basin,Lake Nyasa,Lake Victoria,Pangani,Ruvuma / Southern Coast,Lake Victoria
subvillage,Mnyusi B,Nyamara,Majengo,Mahakamani,Kyanyamisa
region,Iringa,Mara,Manyara,Mtwara,Kagera
region_code,11,20,21,90,18
district_code,5,2,4,63,1
lga,Ludewa,Serengeti,Simanjiro,Nanyumbu,Karagwe
ward,Mundindi,Natta,Ngorika,Nanyumbu,Nyakasimbi
population,109,280,250,58,0
public_meeting,True,NaN,True,True,True
recorded_by,GeoData Consultants Ltd,GeoData Consultants Ltd,GeoData Consultants Ltd,GeoData Consultants Ltd,GeoData Consultants Ltd
scheme_management,VWC,Other,VWC,VWC,NaN
scheme_name,Roman,NaN,Nyumba ya mungu pipe scheme,NaN,NaN
permit,False,True,True,True,True
construction_year,1999,2010,2009,1986,0
extraction_type,gravity,gravity,gravity,submersible,gravity
extraction_type_group,gravity,gravity,gravity,submersible,gravity
extraction_type_class,gravity,gravity,gravity,submersible,gravity
management,vwc,wug,vwc,vwc,other
management_group,user-group,user-group,user-group,user-group,other
payment,pay annually,never pay,pay per bucket,never pay,never pay
payment_type,annually,never pay,per bucket,never pay,never pay
water_quality,soft,soft,soft,soft,soft
quality_group,good,good,good,good,good
quantity,enough,insufficient,enough,dry,seasonal
quantity_group,enough,insufficient,enough,dry,seasonal
source,spring,rainwater harvesting,dam,machine dbh,rainwater harvesting
source_type,spring,rainwater harvesting,dam,borehole,rainwater harvesting
source_class,groundwater,surface,surface,groundwater,surface
waterpoint_type,communal standpipe,communal standpipe,communal standpipe multiple,communal standpipe multiple,communal standpipe
waterpoint_type_group,communal standpipe,communal standpipe,communal standpipe,communal standpipe,communal standpipe

### So this is what it looks like

test and train have the same number of features, but different number of rows

**It looks like we have a set with labels and then the actual values, and then one for the competition to predict and submit**
So the submission is a set to run our model on and submit the values in the same format as the training_set_labels

So I should just use the two training sets for my project.

In [44]:
df_train_1.dtypes

id               int64
status_group    object
dtype: object

In [45]:
df_train_2.dtypes

id                         int64
amount_tsh               float64
date_recorded             object
funder                    object
gps_height                 int64
installer                 object
longitude                float64
latitude                 float64
wpt_name                  object
num_private                int64
basin                     object
subvillage                object
region                    object
region_code                int64
district_code              int64
lga                       object
ward                      object
population                 int64
public_meeting            object
recorded_by               object
scheme_management         object
scheme_name               object
permit                    object
construction_year          int64
extraction_type           object
extraction_type_group     object
extraction_type_class     object
management                object
management_group          object
payment                   object
payment_type              object
water_quality             object
quality_group             object
quantity                  object
quantity_group            object
source                    object
source_type               object
source_class              object
waterpoint_type           object
waterpoint_type_group     object
dtype: object

In [46]:
# Are there any nulls in df_train_2?
df_train_2.isnull().sum()

id                           0
amount_tsh                   0
date_recorded                0
funder                    3635
gps_height                   0
installer                 3655
longitude                    0
latitude                     0
wpt_name                     0
num_private                  0
basin                        0
subvillage                 371
region                       0
region_code                  0
district_code                0
lga                          0
ward                         0
population                   0
public_meeting            3334
recorded_by                  0
scheme_management         3877
scheme_name              28166
permit                    3056
construction_year            0
extraction_type              0
extraction_type_group        0
extraction_type_class        0
management                   0
management_group             0
payment                      0
payment_type                 0
water_quality                0
quality_group                0
quantity                     0
quantity_group               0
source                       0
source_type                  0
source_class                 0
waterpoint_type              0
waterpoint_type_group        0
dtype: int64

We've got nulls. 

Also need to look into the categorical/numerical split.

# Doing a test-train split

In [47]:
# import stuff for test-train split
from sklearn.model_selection import train_test_split

# Which means now I need to figure out how I'm going to do this

# Probably will have to predict the binary group, and then use the train to see how good it did

# So probably combine everything together then split. Would be much easier that way

# Combine df_train_1 and df_train_2
df_train = pd.merge(df_train_1, df_train_2, on='id')
df_train.head().T

# wahoo

,0,1,2,3,4
id,69572,8776,34310,67743,19728
status_group,functional,functional,functional,non functional,functional
amount_tsh,6000,0,25,0,0
date_recorded,2011-03-14,2013-03-06,2013-02-25,2013-01-28,2011-07-13
funder,Roman,Grumeti,Lottery Club,Unicef,Action In A
gps_height,1390,1399,686,263,0
installer,Roman,GRUMETI,World vision,UNICEF,Artisan
longitude,34.9381,34.6988,37.4607,38.4862,31.1308
latitude,-9.85632,-2.14747,-3.82133,-11.1553,-1.82536
wpt_name,none,Zahanati,Kwa Mahundi,Zahanati Ya Nanyumbu,Shuleni
num_private,0,0,0,0,0
basin,Lake Nyasa,Lake Victoria,Pangani,Ruvuma / Southern Coast,Lake Victoria
subvillage,Mnyusi B,Nyamara,Majengo,Mahakamani,Kyanyamisa
region,Iringa,Mara,Manyara,Mtwara,Kagera
region_code,11,20,21,90,18
district_code,5,2,4,63,1
lga,Ludewa,Serengeti,Simanjiro,Nanyumbu,Karagwe
ward,Mundindi,Natta,Ngorika,Nanyumbu,Nyakasimbi
population,109,280,250,58,0
public_meeting,True,NaN,True,True,True
recorded_by,GeoData Consultants Ltd,GeoData Consultants Ltd,GeoData Consultants Ltd,GeoData Consultants Ltd,GeoData Consultants Ltd
scheme_management,VWC,Other,VWC,VWC,NaN
scheme_name,Roman,NaN,Nyumba ya mungu pipe scheme,NaN,NaN
permit,False,True,True,True,True
construction_year,1999,2010,2009,1986,0
extraction_type,gravity,gravity,gravity,submersible,gravity
extraction_type_group,gravity,gravity,gravity,submersible,gravity
extraction_type_class,gravity,gravity,gravity,submersible,gravity
management,vwc,wug,vwc,vwc,other
management_group,user-group,user-group,user-group,user-group,other
payment,pay annually,never pay,pay per bucket,never pay,never pay
payment_type,annually,never pay,per bucket,never pay,never pay
water_quality,soft,soft,soft,soft,soft
quality_group,good,good,good,good,good
quantity,enough,insufficient,enough,dry,seasonal
quantity_group,enough,insufficient,enough,dry,seasonal
source,spring,rainwater harvesting,dam,machine dbh,rainwater harvesting
source_type,spring,rainwater harvesting,dam,borehole,rainwater harvesting
source_class,groundwater,surface,surface,groundwater,surface
waterpoint_type,communal standpipe,communal standpipe,communal standpipe multiple,communal standpipe multiple,communal standpipe
waterpoint_type_group,communal standpipe,communal standpipe,communal standpipe,communal standpipe,communal standpipe